import = ["~/.config/alacritty/catppuccin-latte.toml"]

[env]
TERM = "xterm-256color"
NVIM_APPNAME = "obsidian.nvim"

[shell]
program = "/run/current-system/sw/bin/fish"
args = ["-c", "cd $HOME/Documents/obsidian/ && nvim"]

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 2, y = 4 }
decorations = "buttonless"
opacity = 0.8
blur = true
dynamic_title = false
decorations_theme_variant = "Light"
resize_increments = true
option_as_alt = "Both"

[font]
normal = { family = "UDEV Gothic NF", style = "Regular" }
size = 12.0

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [
  { key = "0", mods = "Alt", action = "ResetFontSize" },
  { key = "=", mods = "Alt|Shift", action = "IncreaseFontSize" },
  { key = "-", mods = "Alt", action = "DecreaseFontSize" },
]
